# Generated by Django 3.0.6 on 2020-06-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='null', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык курса')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('skills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_teacher', to='learning.CourseAreas')),
            ],
            options={
                'verbose_name': 'Язык курса',
                'verbose_name_plural': 'Язык курса',
            },
        ),
        migrations.CreateModel(
            name='CourseShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='course_shots/', verbose_name='Изображени')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Скриншот курса',
                'verbose_name_plural': 'Скриншот к курсам',
            },
        ),
    ]
