# Generated by Django 3.0.7 on 2020-06-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_poll_pollanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Lesson'),
        ),
    ]
