# Generated by Django 3.0.7 on 2020-06-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20200618_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='learning.Lesson'),
        ),
    ]
