# Generated by Django 3.0.6 on 2020-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseshots',
            options={'verbose_name': 'Кадр курса', 'verbose_name_plural': 'Кадры курса'},
        ),
        migrations.AlterField(
            model_name='courseshots',
            name='img',
            field=models.ImageField(upload_to='course_shots/', verbose_name='Изображение'),
        ),
    ]
