# Generated by Django 3.0.6 on 2020-06-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20200609_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.Course', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Reviews', verbose_name='Курс к которому пишут отзыв'),
        ),
    ]
