# Generated by Django 3.0.6 on 2020-06-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20200610_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RenameField(
            model_name='testquestion',
            old_name='question',
            new_name='name',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='parent',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='learning.Lessons', verbose_name='Родитель'),
            preserve_default=False,
        ),
    ]
