# Generated by Django 3.0.6 on 2020-06-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_auto_20200611_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание урока'),
        ),
        migrations.CreateModel(
            name='LessonsInside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст курса')),
                ('img', models.ImageField(upload_to='course_lesson/', verbose_name='Изображение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Lessons', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Информация о курсе',
                'verbose_name_plural': 'Информация о курсе',
            },
        ),
    ]
