# Generated by Django 2.2 on 2020-06-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20200611_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='courseareas',
            options={'verbose_name': 'Області навчання', 'verbose_name_plural': 'Області навчання'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Мова курса', 'verbose_name_plural': 'Мова курса'},
        ),
        migrations.AlterModelOptions(
            name='lessonsinside',
            options={'verbose_name': 'Інформація про курс', 'verbose_name_plural': 'Інформація про курс'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Мова викладання', 'verbose_name_plural': 'Мови викладання'},
        ),
        migrations.AlterModelOptions(
            name='typerating',
            options={'verbose_name': 'Тип оцінювання', 'verbose_name_plural': 'Тип оцінювання'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.TimeField(verbose_name='Тривалість курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='img/', verbose_name='Зображення курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_course', to='learning.Language', verbose_name='Мова курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Назва курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_rating',
            field=models.ManyToManyField(related_name='rating_type', to='learning.TypeRating', verbose_name='Формат перевірки'),
        ),
        migrations.AlterField(
            model_name='courseareas',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='courseareas',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Області'),
        ),
        migrations.AlterField(
            model_name='courseshots',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='courseshots',
            name='img',
            field=models.ImageField(upload_to='course_shots/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Мова курса'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Опис урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='lessonsinside',
            name='img',
            field=models.ImageField(upload_to='course_lesson/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Reviews', verbose_name='Батько'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст відгука'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='typerating',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Тип оцінювання'),
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
