# Generated by Django 2.2 on 2020-06-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20200616_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
