# Generated by Django 2.2 on 2020-06-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_lessons_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='url',
            new_name='slug',
        ),
    ]
